name: 'motor_analytics'
version: '1.0.0'
config-version: 2
profile: 'motor_analytics'

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  motor_analytics:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
